apiVersion: v1
kind: Service
metadata:
  name: couchdb1-org2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: couchdb1.org2.example.com
    external-dns.alpha.kubernetes.io/target: couchdb1.org2.example.com
spec:
  selector:
    app: couchdb1
    tier: database
  ports:
    - protocol: TCP
      targetPort: couchdb1-port
      port: 5984
      nodePort: 30006
      name: couchdb1-port
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb1
  template:
    metadata:
      labels:
        app: couchdb1
        tier: database
        track: stable
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-couchdb1-org2-pvc
      initContainers:
      - name: init-couchdb0-org1
        image: "hyperledger/fabric-couchdb:latest"
        command:
        - "chown"
        - "-R"
        - "couchdb:couchdb"
        - "/opt/couchdb0"
        volumeMounts:
        - mountPath: /opt/couchdb0/data
          name: data
      containers:
        - name: couchdb1-org2
          image: "hyperledger/fabric-couchdb:latest"
          volumeMounts:
          - mountPath: /opt/couchdb/data
            name: data
          env:
            - name: COUCHDB_USER
              value: "CouchOrci1"
            - name: COUCHDB_PASSWORD
              value: "CouchOrciDB01"
          ports:
            - name: couchdb1-port
              containerPort: 5984
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-couchdb1-org2-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-couchdb1-org2-pvc
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

