apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ca.org1.example.com
    external-dns.alpha.kubernetes.io/target: ca.org1.example.com
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "300"
spec:
  #loadBalancerIP: {{ .Values.ingress.addr }}
  #  externalIPs:
  #- {{ .Values.ingress.addr }}
  ports:
  - name: "api"
    port: 7054
    protocol: TCP
  selector:
    service: {{ .Release.Name }}-ca-org1
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: {{ .Release.Name }}-ca-org1
  name: {{ .Release.Name }}-ca-org1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    service: {{ .Release.Name }}-ca-org1
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-ca-org1
      namespace: {{ .Release.Namespace }}
    spec:
      containers:
      - command:
        - fabric-ca-server
        - start
        - --ca.certfile
        - /etc/crypto-config/Orci-Care-Kubernetes/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg1.domain }}/ca/ca.{{ .Values.fabricOrg1.domain }}-cert.pem
        - --ca.keyfile
        - /etc/crypto-config/Orci-Care-Kubernetes/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg1.domain }}/ca/{{ .Values.fabricCa1.keyStoreHash }}_sk
        - -b
        - admin:adminpw
        - -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca.{{ .Values.fabricOrg1.domain }}
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /etc/crypto-config/Orci-Care-Kubernetes/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg1.domain }}/ca/ca.{{ .Values.fabricOrg1.domain }}-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /etc/crypto-config/Orci-Care-Kubernetes/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg1.domain }}/ca/{{ .Values.fabricCa1.keyStoreHash }}_sk
        image: {{ .Values.fabricCa1.image }}:{{ .Values.fabricCa1.tag }}
        name: {{ .Release.Name }}-ca-org1
        ports:
        - containerPort: 7054
        volumeMounts:
        - mountPath: /etc/crypto-config
          name: {{ .Release.Name }}-crypto-config
          readOnly: true
        - mountPath: /etc/crypto-config2
          name: {{ .Release.Name }}-crypto-config2
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-crypto-config
{{ toYaml .Values.cryptoConfigMount | indent 8 }}
      - name: {{ .Release.Name }}-crypto-config2
{{ toYaml .Values.cryptoConfigMount2 | indent 8 }}
